FROM python:3.11-slim

WORKDIR /app

# (optionnel mais souvent utile pour certaines deps)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.web.txt .
RUN pip install --no-cache-dir -r requirements.web.txt

COPY . .

EXPOSE 8501

CMD ["bash", "-lc", "streamlit run src/app_web.py --server.address 0.0.0.0 --server.port ${PORT:-8501} --server.headless true"]
